[versions]
agp = "8.13.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2024.09.00"
okHttp = "5.3.0"
okDownload = "1.0.7"
zip4j = "2.11.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
okdownload = { group = "com.liulishuo.okdownload", name = "okdownload", version.ref = "okDownload" }
okdownload-sqlite = { group = "com.liulishuo.okdownload", name = "sqlite", version.ref = "okDownload" }
okdownload-okhttp = { group = "com.liulishuo.okdownload", name = "okhttp", version.ref = "okDownload" }
okdownload-ktx = { group = "com.liulishuo.okdownload", name = "ktx", version.ref = "okDownload" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }
zip4j = { group = "net.lingala.zip4j", name = "zip4j", version.ref = "zip4j" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
